#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

SH_RED='\033[0;31m'
SH_LBLUE='\033[1;36m'
SH_NC='\033[0m'

printf "${SH_LBLUE}[Running pre-commit hook]${SH_NC}"
echo ""
printf "Use ${SH_LBLUE}--no-verify${SH_NC} option when running ${SH_LBLUE}git commit${SH_NC} to skip this hook."
echo ""
echo ""
echo "Checking if docker service is up and running..."
isServiceUp=$(docker-compose ps --services --filter "status=running" | grep admin-php)

if [ $? -ne 0 ]; then
    printf "${SH_RED}Could not find running docker service.  Aborting...${SH_NC}"
    exit 100
fi

echo "Checking and fixing code style..."

docker-compose exec -T admin-php ./vendor/bin/php-cs-fixer fix --show-progress=dots --no-interaction

if [ $? -ne 0 ]; then
    printf "${SH_RED}Could not fix code style.  Aborting...${SH_NC}"
    exit 101
fi

